#!/bin/bash

# Ansible host:
sudo apt install ansible sshpass
sudo touch /var/log/ansible.log
sudo groupadd ansible
sudo chown root:ansible /var/log/ansible.log
sudo chmod 775 /var/log/ansible.log
sudo usermod vagrant -aG ansible
ansible --version

# Debian:
sudo passwd vagrant

# Ansible:
ssh-keygen -t rsa -b 4096
ssh-copy-id -i /home/vagrant/.ssh/id_rsa vagrant@192.168.15.102

# Ansible-Galaxy (https://galaxy.ansible.com/)
ansible-galaxy install geerlingguy.firewall -p roles/
ansible-galaxy info geerlingguy.firewall -p roles/
cd roles/
ansible-galaxy init teste

# Ansible-Vault
# exemplos:
ansible-vault create passwd.yml
ansible-vault edit passwd.yml
ansible-vault view passwd.yml
ansible-vault decrypt passwd.yml
ansible-vault encrypt passwd.yml

#uso:
cd roles/
ansible-galaxy init create_user
ansible-playbook -i hosts --ask-vault-pass playbook.yml --syntax-check
ansible-playbook -i hosts --ask-vault-pass playbook.yml --check
ansible-playbook -i hosts --ask-vault-pass playbook.yml -v


