---
- hosts: www
  tasks: 
  - name: Remocao de pacotes
    yum:
      name: "{{ packages }}"
      state: absent
    vars: 
      packages:
        - httpd
        - nginx
  - name: Instalacao de pacotes
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
        - httpd
        - nginx
        - vim

...

